# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Test Predator-Prey Game
DESTDIR = ../../x64/Debug
CONFIG += debug
LIBS += -L"." \
    -lC:/Users/HP/source/repos/YuarenArt/Predator-prey-game/x64/Debug/Point2D.obj
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./tests/cph.h \
    ./tests/position/Point2D/Point2DTest.h \

SOURCES += ./main_test.cpp \
    ./tests/position/Point2D/Point2DTest.cpp \
    ./tests/cph.cpp

QT += widgets designer core gui testlib
INCLUDEPATH += ../position/point2D/point2D.h
